name: repo_viewer1
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.0
  flutter_secure_storage: ^5.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.0.2
  flutter_riverpod: ^2.0.2
  freezed_annotation: ^2.1.0
  webview_flutter: ^3.0.3
  flash: ^2.0.5
  auto_route: ^5.0.1
  auto_route_generator: ^5.0.2
  analyzer: ^4.4.6
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.1.0
  build_runner: ^2.2.1
  lint: ^1.10.0

flutter:
  uses-material-design: true
